## Numpy Library

In [15]:
import numpy as np

In [16]:
a = np.array([1,2,3])           # formate to print array function
b = np.array([4,5,6])
print(a)                         # it must be same in a & b variable in array for the operations
print(b)  

[1 2 3]
[4 5 6]


In [17]:
type(a)                       # to find the type of array

numpy.ndarray

### Basics operation of Array

In [18]:
print(a + b)              # array must be same in lenth in variables to perform operations
print(a - b)
print(a * b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [19]:
# creating a 2D (2 dimenction) array      

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [20]:
# creating a 3D (3 dimenction) array

arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [21]:
print(arr.shape)           # shape of the array

(2, 3)


In [22]:
print(arr.ndim)          # dimenction of the array

2


In [24]:
print(arr.dtype)         # data type

int64


In [25]:
np.arange(11)           # to print range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
np.arange(2,11)         # to print range between numbers

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.arange(-10,0)        # can print range of neagative numbers

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])